source 'https://github.com/CocoaPods/Specs.git'

target 'StudyGroup' do

use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'GoogleSignIn'
pod 'Canvas', '~> 0.1.2'
pod 'AlgoliaSearch-Client-Swift', '~> 4.0'

end
